export const environment = {
  production: true,
  apiUrl: 'https://medisupply.hectorfranco.dev',
  apiEndpoints: {
    orders: '/orders',
    customers: '/customers',
    clients: '/clients',
    products: '/products',
    routes: '/routes',
    visitRoutes: '/visits/visit-routes',
    warehouses: '/warehouses',
    visits: '/visits',
    logistics: '/logistics',
    health: '/health',
    inventory: '/inventory',
    authentication: '/auth',
    sellers: '/sellers',
    reports: '/reports',
    suppliers: '/suppliers',
  },
  firebaseApiKey: 'AIzaSyAEcWSpsJOLVQ9lVH5tP1m8XaSq7zIpk5Q',
  firebaseAuthBase: 'https://identitytoolkit.googleapis.com/v1/accounts:signInWithPassword',
  googleMapsApiKey: 'AIzaSyCZPmIyF0n71zTpgsEmet4O0tKvgQMJmjs',
};
